### PR TITLE
Replace deprecated ThrowableProxy with LogEvent#getThrown() in sentry-log4j2

### LINKED ISSUE #5439: Using deprecation in sentry-log4j2
When bumping log4j2 from **log4j2 from 2.20.0 to 2.26.0**

```
> Compilation failed; see the compiler output below.
  /home/runner/work/sentry-java/sentry-java/sentry-log4j2/src/main/java/io/sentry/log4j2/SentryAppender.java:44: warning: [deprecation] ThrowableProxy in org.apache.logging.log4j.core.impl has been deprecated
  import org.apache.logging.log4j.core.impl.ThrowableProxy;
                                     
  1 error
  3 warnings
```

[https://github.com/getsentry/sentry-java/actions/runs/25841919902/job/75928866128?pr=5435](<https://github.com/getsentry/sentry-java/actions/runs/25841919902/job/75928866128?pr=5435>)

### PR DESCRIPTION
**Pull request by sahasan95**
…-log4j2

## :scroll: Description
Replaces the deprecated `ThrowableProxy` class with `LogEvent#getThrown()` in `SentryAppender`.

## :bulb: Motivation and Context
`ThrowableProxy` is deprecated in log4j2. The only usage in `SentryAppender` was calling
`.getThrowable()` on it to extract the underlying `Throwable`. `LogEvent` already exposes 
this directly via `getThrown()`, which is documented as a convenience method for exactly 
that purpose, so `ThrowableProxy` can be dropped entirely.

* resolves: #5439

## :green_heart: How did you test it?
Ran the existing `sentry-log4j2` test suite (`./gradlew :sentry-log4j2:test`) — all tests pass.

## :pencil: Checklist
- [x] I added GH Issue ID _&_ Linear ID
- [ ] I added tests to verify the changes.
- [x] No new PII added or SDK only sends newly added PII if `sendDefaultPII` is enabled.
- [ ] I updated the docs if needed.
- [ ] I updated the wizard if needed.
- [ ] Review from the native team if needed.
- [x] No breaking change or entry added to the changelog.
- [x] No breaking change for hybrid SDKs or communicated to hybrid SDKs.
- [ ] Public API changes reviewed by another Mobile SDK team member or implemented according to the [develop docs](https://develop.sentry.dev/) spec.

## :crystal_ball: Next steps
N/A

### CODE REVIEW

File: sentry-log4j2/src/main/java/io/sentry/log4j2/SentryAppender.java [hunk 1]
```diff
@@ -274,13 +273,12 @@ protected void captureLog(@NotNull LogEvent loggingEvent) {
     event.setLogger(loggingEvent.getLoggerName());
     event.setLevel(formatLevel(loggingEvent.getLevel()));
 
-    final ThrowableProxy throwableInformation = loggingEvent.getThrownProxy();
-    if (throwableInformation != null) {
+    final Throwable thrown = loggingEvent.getThrown();
```
Comment (markushi) [inline sentry-log4j2/src/main/java/io/sentry/log4j2/SentryAppender.java]: `nit`
```suggestion
    final @Nullable Throwable thrown = loggingEvent.getThrown();
```

**Review by markushi — COMMENTED** [review]
Looking good, could you add entry to CHANGELOG.md as well?

**Review by adinauer — APPROVED** [review]
Thank you for the contribution! LGTM
