### ISSUE TITLE
Using deprecation in sentry-log4j2

### ISSUE THREAD

**Issue by runningcode** [getsentry/sentry-java#5439]
When bumping log4j2 from **log4j2 from 2.20.0 to 2.26.0**

```
> Compilation failed; see the compiler output below.
  /home/runner/work/sentry-java/sentry-java/sentry-log4j2/src/main/java/io/sentry/log4j2/SentryAppender.java:44: warning: [deprecation] ThrowableProxy in org.apache.logging.log4j.core.impl has been deprecated
  import org.apache.logging.log4j.core.impl.ThrowableProxy;
                                     
  1 error
  3 warnings
```

[https://github.com/getsentry/sentry-java/actions/runs/25841919902/job/75928866128?pr=5435](<https://github.com/getsentry/sentry-java/actions/runs/25841919902/job/75928866128?pr=5435>)

**Comment by sahasan95** [comment]
Hi, I'd like to take this on if available. Looking at SentryAppender.java, the only usage of ThrowableProxy is loggingEvent.getThrownProxy().getThrowable() to extract the underlying Throwable. Log4j2's LogEvent interface exposes this directly via getThrown() (documented as "convenience method for ThrowableProxy.getThrowable()"), so I think we can drop ThrowableProxy entirely here. I can open a PR with that change unless there's a reason to keep the proxy reference, and will reference this issue in the PR description.

**Comment by adinauer** [comment]
Yes please, I just checked and using `getThrown` should be compatible all the way back to `2.0`. Thank you!
