### ISSUE TITLE
NoSuchMethod Error in SessionReplay Compose usage

### ISSUE THREAD

**Issue by kylannjohnson** [getsentry/sentry-java#4480]
### Integration

other

### Build System

Gradle

### AGP Version

8.10.1

### Proguard

Enabled

### Version

8.13.2

### Steps to Reproduce

1. Enable Session Replay (1.0 sample rate)
2. compile with Compose BOM `2025.06.00`

Launch app and see errors in Sentry

### Expected Result

No errors reported

### Actual Result

Here's the stack trace

```
Error traversing Compose tree. Most likely you're using an unsupported version of
androidx.compose.ui:ui. The minimum supported version is 1.5.0. If it's a newer
version, please open a github issue with the version you're using, so we can add
support for it.
java.lang.NoSuchMethodError: No virtual method getCollapsedSemantics$ui_release()Landroidx/compose/ui/semantics/SemanticsConfiguration; in class Landroidx/compose/ui/node/LayoutNode; or its super classes (declaration of 'androidx.compose.ui.node.LayoutNode' appears in /data/app/~~RoGfUvA4dSzKSQrkECHzQw==/com.americanexpress.android.acctsvcs.us.debug-I-AiGswj_d9O9J-cz95wNg==/base.apk)
	at io.sentry.android.replay.viewhierarchy.ComposeViewHierarchyNode.fromComposeNode(ComposeViewHierarchyNode.kt:86)
	at io.sentry.android.replay.viewhierarchy.ComposeViewHierarchyNode.traverse(ComposeViewHierarchyNode.kt:214)
	at io.sentry.android.replay.viewhierarchy.ComposeViewHierarchyNode.fromView(ComposeViewHierarchyNode.kt:187)
	at io.sentry.android.replay.util.ViewsKt.traverse(Views.kt:36)
	at io.sentry.android.replay.util.ViewsKt.traverse(Views.kt:53)
	at io.sentry.android.replay.util.ViewsKt.traverse(Views.kt:53)
	at io.sentry.android.replay.util.ViewsKt.traverse(Views.kt:53)
	at io.sentry.android.replay.util.ViewsKt.traverse(Views.kt:53)
	at io.sentry.android.replay.util.ViewsKt.traverse(Views.kt:53)
	at io.sentry.android.replay.util.ViewsKt.traverse(Views.kt:53)
	at io.sentry.android.replay.util.ViewsKt.traverse(Views.kt:53)
	at io.sentry.android.replay.util.ViewsKt.traverse(Views.kt:53)
	at io.sentry.android.replay.util.ViewsKt.traverse(Views.kt:53)
	at io.sentry.android.replay.util.ViewsKt.traverse(Views.kt:53)
	at io.sentry.android.replay.util.ViewsKt.traverse(Views.kt:53)
	at io.sentry.android.replay.ScreenshotRecorder.capture$lambda$3$lambda$2(ScreenshotRecorder.kt:126)
	at io.sentry.android.replay.ScreenshotRecorder.$r8$lambda$MDQmuOd307mEqBQX9borkhY8e1E(ScreenshotRecorder.kt:0)
	at io.sentry.android.replay.ScreenshotRecorder$$ExternalSyntheticLambda2.onPixelCopyFinished(R8$$SyntheticClass:0)
	at android.view.PixelCopy$1.lambda$onCopyFinished$0(PixelCopy.java:193)
	at android.view.PixelCopy$1$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:995)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loopOnce(Looper.java:248)
	at android.os.Looper.loop(Looper.java:338)
	at android.app.ActivityThread.main(ActivityThread.java:9067)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:593)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:932)
```

**Comment by markushi** [comment]
@kylannjohnson thanks for reporting this issue. Looks like a dup of https://github.com/getsentry/sentry-java/issues/4467, where some internal changes to Compose broke our masking logic.
