### ISSUE TITLE
Exception in Android Emulator: Failed resolution of: Lio/sentry/event/BreadcrumbBuilder

### ISSUE THREAD

**Issue by benjamingr** [getsentry/sentry-java#531]
Hey, I'm building an aar library and I'm using Sentry Java for logging.

I'm getting the following exception:

     java.lang.NoClassDefFoundError: Failed resolution of: Lio/sentry/event/BreadcrumbBuilder;

When I'm trying to create a BreadcrumbBuilder. I've tried updating sentry-java to the latest version which didn't help.

**Comment by bretthoerner** [comment]
Weird, that class definitely exists in the `sentry` package. I don't know a lot about AARs, are you using `sentry-android` or the base `sentry` library? If you're using `sentry-android` is it pulling in dependencies for you? You'll also need `sentry` to get that class.

**Comment by benjamingr** [comment]
Hey, everything worked before, I updated Gradle and Android Studio and afterwards these errors started showing.

I ended up actually guarding against them by catching the `NoClassDefFoundError` in case it happens. I'm not sure why it happens or how to reproduce it consistently. 

After updating to 1.6.1 and copying the project over to a new project things seem to work, this only happened when including the AAR in another project and not when including a reference.
